on:
  push:
    branches:
      - release # Update to match your branch name
name: Build the application

jobs:
  build:
    name: Build and release new application
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "21"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.2" # Updated to newer Flutter version
          channel: "stable"
      - run: |
          cd sdgp_infratrack_clone
          flutter pub get
          flutter build apk --release --split-per-abi

      - name: List build directory contents (for debugging)
        run: |
          find sdgp_infratrack_clone/build -type f -name "*.apk" | sort

      - name: Push to releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "sdgp_infratrack_clone/build/*.apk"
          tag: v0.0.1
          token: ${{secrets.TOKEN}}
