on:
  push:
    branches:
      - release # Update to match your branch name
name: Build the application

jobs:
  build:
    name: Build and release new application
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.19.3" # Updated to newer Flutter version
          channel: "stable"

      - name: Get dependencies
        run: |
          cd sdgp_infratrack_clone
          flutter pub get

      # - name: Check for any formatting issues
      #   run: |
      #     cd sdgp_infratrack_clone
      #     flutter format --set-exit-if-changed .

      # - name: Statically analyze the Dart code
      #   run: |
      #     cd sdgp_infratrack_clone
      #     flutter analyze .

      # - name: Run tests
      #   run: |
      #     cd sdgp_infratrack_clone
      #     flutter test

      - name: Build APK
        run: |
          cd sdgp_infratrack_clone
          flutter build apk --release --split-per-abi

      - name: List build directory contents (for debugging)
        run: |
          find sdgp_infratrack_clone/build -type f -name "*.apk" | sort

      - name: Push to releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/*.apk"
          tag: v0.0.1
          token: ${{secrets.GITHUB_TOKEN}}
