on:
  push:
    branches:
      - release # Update to match your branch name
name: Build the application

jobs:
  build:
    name: Build and release new application
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "21"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.2"
          channel: "stable"

      - run: |
          cd sdgp_infratrack_clone
          flutter pub get
          flutter build apk --release --split-per-abi

      - name: List build directory contents (for debugging)
        run: |
          find sdgp_infratrack_clone/build -type f -name "*.apk" | sort

      - name: Delete existing releases
        uses: dev-drprasad/delete-older-releases@v0.2.0
        with:
          keep_latest: 0 # Delete all releases
          delete_tags: true #delete tags associated with the releases
          repo: ${{ github.repository }}
          token: ${{ secrets.TOKEN }}

      - name: Generate version
        id: version
        run: |
          echo "VERSION=v0.1.01" >> $GITHUB_OUTPUT

      - name: Push to releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "sdgp_infratrack_clone/build/app/outputs/flutter-apk/app-*.apk"
          tag: ${{ steps.version.outputs.VERSION }}
          token: ${{secrets.TOKEN}}
