on:
  push:
    branches:
      - release
name: Build the application

jobs:
  build:
    name: Build and release new application
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.2"
          channel: "stable"

      - name: Get dependencies
        run: |
          cd sdgp_infratrack_clone
          flutter pub get

      # - name: Check for any formatting issues
      #   run: flutter format --set-exit-if-changed .

      # - name: Statically analyze the Dart code
      #   run: flutter analyze .

      # - name: Run tests
      #   run: flutter test

      - name: Build APK
        run: |
          cd sdgp_infratrack_clone
          flutter build apk --release --split-per-abi

      - name: Push to releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/output/apk/release/*"
          tag: v0.0.1
          token: ${{secrets.TOKEN}}
